

function cadastrar(){
 let nome=document.getElementById ("nome");
 if(nome ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 let cep=document.getElementById("cep");
 if(cep ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 let rua=document.getElementById("rua");
 if(rua ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 let bairro=document.getElementById("bairro");
 if(bairro ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 let estado=document.getElementById("estado");
 if(estado ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 let cidade=document.getElementById("cidade");
 if(cidade ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 let email=document.getElementById("email");
 if(email ==""){
    alert(Campo com preenchimento obrigatório);    
     }

 

}